

export const LIMA_ALIASES = {

  "utec":   "universidad de ingenieria y tecnologia",
  "pucp":   "pontificia universidad católica del perú",
  "puc":    "pontificia universidad católica del perú",
  "unmsm":  "universidad nacional mayor de san marcos",
  "san marcos": "universidad nacional mayor de san marcos",
  "uni":    "universidad nacional de ingenieria",
  "upc":    "universidad peruana de ciencias aplicadas",
  "ul":     "universidad de lima",
  "u de lima": "universidad de lima",
  "usmp":   "universidad san martín de porres",
  "utp":    "universidad tecnológica del perú",
  "uigv":   "universidad inca garcilaso de la vega",
  "unfv":   "universidad nacional federico villarreal",
  "upch":   "universidad peruana cayetano heredia",
  "upsjb":  "universidad privada san juan bautista",
  "uap":    "universidad alas peruanas",
  "ucv":    "universidad césar vallejo",
  "upn":    "universidad privada del norte",
  "esan":   "universidad esan",
  "udep":   "universidad de piura lima",
  "centrum":"centrum pucp lima",
  "senati": "senati lima",
  "tecsup": "tecsup lima",
  "cibertec":"cibertec lima",
  "isil":   "isil lima",


  "jockey": "jockey plaza lima",
  "larcomar":"larcomar miraflores",
  "larco mar":"larcomar miraflores",
  "megaplaza":"megaplaza lima norte",
  "mega plaza":"megaplaza lima norte",
  "mega":   "megaplaza lima norte",
  "plaza norte":"plaza lima norte",
  "plaza lima norte":"plaza lima norte",
  "plaza lima sur":"plaza lima sur",
  "plaza sur":"plaza lima sur",
  "open plaza":"open plaza angamos",
  "open plaza angamos":"open plaza angamos",
  "open plaza chorrillos":"open plaza chorrillos",
  "real plaza salaverry":"real plaza salaverry",
  "real plaza":"real plaza salaverry",
  "real plaza primavera":"real plaza primavera",
  "real plaza puruchuco":"real plaza puruchuco",
  "plaza san miguel":"plaza san miguel lima",
  "plaza camacho":"plaza camacho la molina",
  "camino real":"centro comercial camino real",
  "cc camino real":"centro comercial camino real",
  "aurora":"centro comercial aurora",
  "boulevard":"boulevard de asia",
  "cc risso":"centro comercial risso",
  "cc angamos":"open plaza angamos",


  "wong miraflores":   "wong miraflores",
  "wong san isidro":   "wong san isidro",
  "metro san isidro":  "metro san isidro",
  "vivanda surco":     "vivanda surco",
  "tottus san borja":  "tottus san borja",
  "plaza vea surco":   "plaza vea surco",


  "rebagliati":   "hospital edgardo rebagliati martins",
  "almenara":     "hospital guillermo almenara irigoyen",
  "loayza":       "hospital arzobispo loayza",
  "dos de mayo":  "hospital dos de mayo",
  "2 de mayo":    "hospital dos de mayo",
  "cayetano":     "hospital cayetano heredia",
  "cayetano heredia": "hospital cayetano heredia",
  "insn":         "instituto nacional de salud del niño",
  "hosp del niño":"instituto nacional de salud del niño",
  "inen":         "instituto nacional de enfermedades neoplásicas",
  "incor":        "instituto nacional cardiovascular",
  "inr":          "instituto nacional de rehabilitacion",
  "clinica san pablo":"clinica san pablo",
  "clinica ricardo palma":"clinica ricardo palma",
  "clinica internacional":"clinica internacional lima",
  "clinica good hope":"clinica good hope miraflores",
  "clinica javier prado":"clinica javier prado",
  "clinica angloamericana":"clinica angloamericana san isidro",
  "angloamericana":"clinica angloamericana san isidro",
  "clinica maison de sante":"clinica maison de sante lima",
  "maison de sante":"clinica maison de sante lima",


  "jia":          "aeropuerto internacional jorge chávez",
  "jorge chavez": "aeropuerto internacional jorge chávez",
  "aeropuerto":   "aeropuerto internacional jorge chávez",
  "terminal plaza norte":"terminal terrestre plaza norte",
  "terminal yerbateros":"terminal terrestre yerbateros",
  "terminal javier prado":"terminal terrestre javier prado",


  "estadio nacional":"estadio nacional lima",
  "monumental":   "estadio monumental lima",
  "alejandro villanueva":"estadio alejandro villanueva",
  "matute":       "estadio alejandro villanueva",
  "san marcos estadio":"estadio san marcos lima",
  "complejo deportivo videna":"videna san luis",
  "videna":       "videna san luis",


  "mali":         "museo de arte de lima",
  "mam":          "museo de arte moderno lima",
  "larco":        "museo larco lima",
  "museo larco":  "museo larco lima",
  "museo de la nacion":"museo de la nacion lima",
  "lugar de la memoria":"lugar de la memoria lima",
  "lum":          "lugar de la memoria lima",
  "cine planet":  "cineplanet lima",
  "ccpb":         "centro cultural pucp lima",


  "parque kennedy":"parque kennedy miraflores",
  "kennedy":      "parque kennedy miraflores",
  "circuito magico":"parque de la reserva lima",
  "circuito magico del agua":"parque de la reserva lima",
  "parque de la reserva":"parque de la reserva lima",
  "parque reducto":"parque reducto miraflores",
  "parque de las leyendas":"parque de las leyendas lima",
  "leyendas":     "parque de las leyendas lima",
  "zoo":          "parque de las leyendas lima",
  "zoologico":    "parque de las leyendas lima",
  "espiritu santo":"parque espiritu santo barranco",
  "alameda chabuca":"alameda chabuca granda lima",
  "parque italia":"parque italia lima",
  "parque universitario":"parque universitario lima",
  "bosque el olivar":"bosque el olivar san isidro",
  "el olivar":    "bosque el olivar san isidro",


  "huaca pucllana":"huaca pucllana miraflores",
  "pucllana":     "huaca pucllana miraflores",
  "huaca huallamarca":"huaca huallamarca san isidro",
  "huallamarca":  "huaca huallamarca san isidro",
  "huaca mateo salado":"huaca mateo salado lima",
  "pachacamac":   "pachacamac lima",


  "ovalo gutierrez":"óvalo gutiérrez miraflores",
  "ovalo monitor":"óvalo monitor san isidro",
  "ovalo higuereta":"óvalo higuereta surco",
  "ovalo de la aviacion":"óvalo aviación san borja",
  "ovalo quiñones":"óvalo quiñones san borja",


  "plaza mayor":  "plaza mayor lima",
  "plaza de armas":"plaza mayor lima",
  "plaza san martin":"plaza san martín lima",
  "plaza 2 de mayo":"plaza dos de mayo lima",
  "plaza dos de mayo":"plaza dos de mayo lima",
  "plaza grau":   "plaza grau lima",
  "plaza merino": "plaza merino lima",


  "villa maria":  "colegio villa maria lima",
  "santa maria":  "colegio santa maria lima",
  "markham":      "colegio markham lima",
  "san agustin":  "colegio san agustín lima",
  "la salle":     "colegio la salle lima",
  "recoleta":     "colegio recoleta lima",
  "santa rosa":   "colegio santa rosa lima",
  "roosevelt":    "colegio franklin d roosevelt lima",
  "newton":       "colegio newton lima",
  "raimondi":     "colegio antonio raimondi lima",
  "santa ursula": "colegio santa ursula lima",
  "pestalozzi":   "colegio pestalozzi lima",
  "peruano britanico":"colegio peruano britanico lima",
  "britanico":    "colegio peruano britanico lima",
  "peruano aleman":"colegio peruano aleman lima",
  "aleman":       "colegio peruano aleman lima",
  "peruano japones":"colegio peruano japones lima",
  "franco peruano":"colegio franco peruano lima",
  "san silvestre":"colegio san silvestre lima",


  "congreso":     "congreso de la república lima",
  "palacio de gobierno":"palacio de gobierno lima",
  "municipalidad lima":"municipalidad metropolitana de lima",
  "muni lima":    "municipalidad metropolitana de lima",
  "poder judicial":"poder judicial lima",
  "ministerio de educacion":"ministerio de educacion lima",
  "minedu":       "ministerio de educacion lima",
  "minsa":        "ministerio de salud lima",
  "sunat":        "sunat lima",
  "reniec":       "reniec lima",
  "migraciones":  "superintendencia de migraciones lima",


  "surco":        "Santiago de Surco",
  "la molina":    "La Molina Lima",
  "ate":          "Ate Lima",
  "sjl":          "San Juan de Lurigancho Lima",
  "sjm":          "San Juan de Miraflores Lima",
  "san juan de lurigancho":"San Juan de Lurigancho Lima",
  "san juan de miraflores":"San Juan de Miraflores Lima",
  "villa el salvador":"Villa El Salvador Lima",
  "ves":          "Villa El Salvador Lima",
  "vmarte":       "Villa María del Triunfo Lima",
  "villa maria del triunfo":"Villa María del Triunfo Lima",
  "chorrillos":   "Chorrillos Lima",
  "rimac":        "Rímac Lima",
  "el rimac":     "Rímac Lima",
  "la victoria":  "La Victoria Lima",
  "breña":        "Breña Lima",
  "brena":        "Breña Lima",
  "lince":        "Lince Lima",
  "pueblo libre": "Pueblo Libre Lima",
  "jesus maria":  "Jesús María Lima",
  "magdalena":    "Magdalena del Mar Lima",
  "san miguel":   "San Miguel Lima",
  "callao":       "Callao Perú",
  "bellavista":   "Bellavista Callao",
  "la perla":     "La Perla Callao",
  "mi peru":      "Mi Perú Callao",


  "larco herrera":"hospital victor larco herrera magdalena",
  "larco herrera hospital":"hospital victor larco herrera magdalena",
  "la parada":    "mercado la parada lima",
  "surquillo mercado":"mercado de surquillo",
  "bajada balta": "bajada balta miraflores",
  "malecon": "malecón cisneros miraflores",
  "malecon cisneros":"malecón cisneros miraflores",
  "malecon de miraflores":"malecón cisneros miraflores",
  "faro de la marina":"faro de la marina miraflores",
  "parque amor":  "parque del amor miraflores",
  "parque del amor":"parque del amor miraflores",
  "costa verde":  "circuito de playas costa verde lima",
  "chorrillos playa":"playa los yuyos chorrillos",
};
